server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: artist-service
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

queue:
  artist:
    name: ArtistQueue

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

management:
  tracing:
    sampling:
      probability: 1.0
logging:
  logging:
    pattern:
      level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    org:
      springframework:
        web: DEBUG
