server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: playlist-service
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

queue:
  artist:
    name: ArtistQueue
  song:
    name: SongQueue

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

management:
  tracing:
    sampling:
      probability: 1.0
logging:
  logging:
    pattern:
      level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    org:
      springframework:
        web: DEBUG

resilience4j:
  cicuitbreaker:
    instances:
      song:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        allowHealthIndicatorToFail: false
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      song:
        waitDuration: 1000
        maxAttempts: 3
        retryExceptions:
          - feign.FeignException$InternalServerError
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2
