server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vlambo3/my-spotify
          default-label: main
          search-paths: configs

